routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/send/{project}', 'HomeController@send')->name('send');
Route::get('/test', 'HomeController@test')->name('test');

Route::get('/about', 'HomeController@about')->name('about');
Route::get('/dreamfund', 'HomeController@dreamfund')->name('dreamfund');
Route::get('/happening', 'HomeController@happening')->name('happening');
Route::get('/media', 'HomeController@media')->name('media');
Route::get('/photos', 'HomeController@photos')->name('photos');
Route::get('/videos', 'HomeController@videos')->name('videos');
Route::any('/explore', 'ProjectController@explore')->name('explore');
Route::any('/journal', 'HomeController@journal')->name('journal');
Route::any('/journal/archive/{year?}/{month?}', 'HomeController@journal_archive')->name('journal.archive');
Route::any('/journal/detail', 'HomeController@journal_detail')->name('journal.detail');

Route::get('/journal/year/{year?}/{month?}', 'JournalController@list');

Route::any('/media/press', 'HomeController@media_press')->name('media.press');
Route::get('/presses/year/{year?}', 'PressController@list');

Route::resource('themes', 'JournalThemeController');

Route::any('/contactus', 'HomeController@contactus')->name('contactus');
Route::any('/partnership', 'HomeController@partnership')->name('partnership');
Route::any('/getinvolved', 'HomeController@getinvolved')->name('getinvolved');

Route::get('/verify/{code}', 'HomeController@verify')->name('verify');
Route::get('/sms/verify', 'HomeController@verify_sms')->name('sms.confirm');
Route::get('/sms/resend', 'HomeController@resend_code')->name('sms.resend');
Route::post('/sms/confirm', 'HomeController@confirm_sms')->name('sms.confirm.code');
Route::get('/email/resend', 'HomeController@resend_email')->name('email.resend');
Route::get('/email/test/{project}', 'HomeController@email_test')->name('email.test');



//facebook auth
Route::get('auth/facebook', 'Auth\FacebookController@redirectToFacebook');
Route::get('auth/facebook/callback', 'Auth\FacebookController@handleFacebookCallback');

//google auth
Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/fill', 'HomeController@fill')->name('fill');
    Route::post('/auth/update', 'HomeController@auth_update')->name('auth.update');
    Route::post('/phone/update', 'HomeController@phone_update')->name('phone.update');
    Route::get('/phone/change', 'HomeController@phone_change')->name('phone.change');
});

Route::group( ['middleware' => ['auth', 'checkAccount']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');

    Route::get('/projects/me',  'ProjectController@index_me')->name('projects.me');
    Route::get('/projects/joined',  'ProjectController@index_joined')->name('projects.joined');

    Route::get('/profile',  'ProfileController@profile')->name('profile');
    Route::get('/profile/edit',  'ProfileController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'ProfileController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'ProfileController@profile_update')->name('profile.update');
    Route::put('/account/update',  'ProfileController@account_update')->name('account.update');
    Route::put('/profile/password/update',  'ProfileController@profile_pw_update')->name('profile.pw_update');
    Route::put('/profile/disaster',  'ProfileController@profile_disaster')->name('profile.disaster');
    Route::put('/profile/update/categories', 'ProfileController@update_categories')->name('profile.update.categories');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('projects', 'ProjectController');

    Route::resource('presses', 'PressController');
    Route::get('/presses/{id}/restore', 'PressController@restore')->name('presses.restore');
    Route::put('/presses/{id}/banner', 'PressController@image_update')->name('presses.image.update');
    Route::delete('/presses/{id}/banner', 'PressController@image_delete')->name('presses.image.delete');

    Route::get('/projects/{project}/status/{status}', 'ProjectController@update_status')->name('projects.update.status');

    Route::get('/projects/join/{project}', 'ProjectController@join_project')->name('projects.join');
    Route::get('/projects/leave/{project}', 'ProjectController@leave_project')->name('projects.leave');

    Route::get('/projects/subscribe/{project}', 'ProjectController@subscribe_project')->name('projects.subscribe');
    Route::get('/projects/unsubscribe/{project}', 'ProjectController@unsubscribe_project')->name('projects.unsubscribe');

    Route::put('/projects/update/{project}/detail', 'ProjectController@update_detail')->name('projects.update.detail');
    Route::put('/projects/update/{project}/location', 'ProjectController@update_location')->name('projects.update.location');
    Route::put('/projects/update/{project}/volunteer', 'ProjectController@update_volunteer')->name('projects.update.volunteer');
    Route::put('/projects/update/{project}/categories', 'ProjectController@update_categories')->name('projects.update.categories');
    Route::put('/projects/update/{project}/type', 'ProjectController@update_type')->name('projects.update.type');


    //cms
    Route::resource('banners', 'BannerController');
    Route::get('/banners/{id}/restore', 'BannerController@restore')->name('banners.restore');

    Route::resource('journals', 'JournalController')->except([
        'show'
    ]);

    Route::get('/journals/{id}/restore', 'JournalController@restore')->name('journals.restore');
    Route::put('/journals/{id}/banner/main/image', 'JournalController@journal_main_image_update')->name('journals.main.image.update');
    Route::put('/journals/{id}/banner/author/image', 'JournalController@journal_author_image_update')->name('journals.author.image.update');

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser')->name('datatables.users');
    Route::get('datatables/getCategories', 'DatatablesController@getCategories')->name('datatables.categories');
    Route::get('datatables/getProjects', 'DatatablesController@getProjects')->name('datatables.projects');
    Route::get('datatables/getPress', 'DatatablesController@getPresses')->name('datatables.presses');
    Route::get('datatables/getMyProjects', 'DatatablesController@getMyProjects')->name('datatables.projects.me');
    Route::get('datatables/getMyJoinedProjects', 'DatatablesController@getMyJoinedProjects')->name('datatables.projects.joined');
    Route::get('datatables/getJoined/{project}', 'DatatablesController@getJoined')->name('datatables.joined');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');


});

Route::resource('projects', 'ProjectController')->only([
    'show'
]);

Route::resource('journals', 'JournalController')->only([
    'show'
]);

resources/views/contactus.blade.php
@extends('layouts.front.master') @section('content')
<!--  header image      -->
<div class="container-fluid p-0 ">
    <div class="row header-img align-items-center justify-content-center" style="background-image: url(/img/contact/contactbg.jpg)">
        <div class="col-md-12 text-center">
            <h1 class="white-text text-shadow">CONTACT US</h1>
            <h5 class="white-text text-shadow">Contact us for any inquiries of feedback.</h5>
        </div>
    </div>
</div>
<!--  end  -->

<!--  get in touch  -->
<div id="getin" class="container-fluid p-0 bluesea-bg pt-5 pb-5">
    <div class="container">
        <div class="row mt-4">
            <div class="col-sm-12 col-md-6 col-lg-6 p-2 m-0">
                <div class="contact-box rounded border white-bg pb-4 pt-3">
                    <div class="row mt-4">
                        <div class="col-sm-4 offset-sm-4 col-lg-3 offset-lg-4">
                            <img src="img/contact/line.png" class="img-fluid m-3" />
                        </div>
                        <div class="col-sm-12 text-center mt-4">
                            <h4 class="red-text mb-3">General Line</h4>
                            <a class="blue-text">+603 8064 4488</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 p-2 m-0">
                <div class="contact-box rounded border white-bg pb-4 pt-3">
                    <div class="row mt-4">
                        <div class="col-sm-4 offset-sm-4 col-lg-3 offset-lg-4">
                            <img src="img/contact/address.png" class="img-fluid m-3" />
                        </div>
                        <div class="col-sm-12 text-center mt-4">
                            <h4 class="red-text mb-3">Address</h4>
                            <a class="blue-text">Rubix, Jalan TPP 1/7 <br> Taman Perindustrian Puchong <br> 47100 Selangor</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row pb-5">
                <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                    <div class="contact-box rounded border white-bg pb-4 pt-3">
                        <div class="row mt-5">
                            <div class="col-sm-4 offset-sm-4 col-lg-6 offset-lg-2">
                                <img src="img/contact/brand.png" class="img-fluid m-3" />
                            </div>
                            <div class="col-sm-12 text-center mt-4">
                                <h4 class="red-text mb-3">Branding & PR</h4>
                                <a class="blue-text" href="mailto:bmg@volunteermalaysia.my" style="font-size: 10pt">bmg@volunteermalaysia.my</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                        <div class="contact-box rounded border white-bg pb-4 pt-3">
                            <div class="row mt-5">
                                <div class="col-sm-4 offset-sm-4 col-lg-6 offset-lg-2">
                                    <img src="img/contact/csd.png" class="img-fluid m-3" />
                                </div>
                                <div class="col-sm-12 text-center mt-4">
                                    <h4 class="red-text mb-3">Corporate Services</h4>
                                    <a class="blue-text" href="mailto:csd@volunteermalaysia.my" style="font-size: 10pt">csd@volunteermalaysia.my</a>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                        <div class="contact-box rounded border white-bg pb-4 pt-3">
                            <div class="row mt-5">
                                <div class="col-sm-4 offset-sm-4 col-lg-6 offset-lg-2">
                                    <img src="img/contact/outreach.png" class="img-fluid m-3" />
                                </div>
                                <div class="col-sm-12 text-center mt-4">
                                    <h4 class="red-text mb-3">Outreach</h4>
                                    <a class="blue-text text-center" href="mailto:outreach@volunteermalaysia.my" style="font-size: 10pt">outreach@volunteermalaysia.my</a>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                        <div class="contact-box rounded border white-bg pb-4 pt-3">
                            <div class="row mt-5">
                                <div class="col-sm-4 offset-sm-4 col-lg-6 offset-lg-2">
                                    <img src="img/contact/hr.png" class="img-fluid m-3" />
                                </div>
                                <div class="col-sm-12 text-center mt-4">
                                    <h4 class="red-text mb-3">Human Resources</h4>
                                    <a class="blue-text" href="mailto:hr@volunteermalaysia.my" style="font-size: 10pt">hr@volunteermalaysia.my</a>
                                </div>
                            </div>
                        </div>
                </div>
        </div>
    </div>
</div>
<!--  end  -->


@endsection @section('js') @parent @endsection

resources/views/footer.blade.php
<footer class="footer-distributed white-bg">

<!--
<div class="footer-right">

    <a href="https://www.facebook.com/volunteermy/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/volunteermy" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.instagram.com/volunteermalaysia/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.youtube.com/channel/UCdzKT8BJn225_0UdGt1NaeA" target="_blank"><i class="fab fa-youtube"></i></a>
</div>
-->

<div class="footer-left">
    <p>Volunteer Malaysia &copy; 2018</p>
</div>

</footer>

resources/views/getinvolved.blade.php
@extends('layouts.front.master') @section('content')
<!--  header image      -->
<div class="container-fluid p-0 ">
    <div class="row header-img align-items-center justify-content-center" style="background-image: url(/img/dremfund/dre1m_header.jpg)">
        <div class="col-md-12 text-center">
            <h1 class="white-text text-shadow">GET INVOLVED</h1>
            <h5 class="white-text text-shadow">Join our cause to do something good.</h5>
        </div>
    </div>
</div>
<!--  end  -->

<!--  why volunteer  -->
<div id="whyvolunteer" class="container-fluid p-0 blue-bg pt-5 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 pt-5">
                <h1 class="white-text">WHY VOLUNTEER WITH US?</h1>
                <p class="white-text pt-3">People choose to volunteer for a variety of reasons. For some it offers the chance to give something back to the community or make a difference to the people around them. For others it provides an opportunity to develop new skills or build on existing experience and knowledge. Regardless of the motivation, what unites them all is that they find it both challenging and rewarding. Our volunteer initiatives are centered on our
                    four pillars:</p>
            </div>
        </div>
        <div class="row mt-4 pb-5">
            <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                <div class="drem-box rounded border box-shadow white-bg pb-4 pt-3 hover-zoom">
                    <div class="row">
                        <div class="col-sm-4 offset-sm-4 col-lg-7 offset-lg-2">
                            <img src="img/dremfund/arts-01.png" class="img-fluid m-3" />
                        </div>
                        <div class="col-sm-12 text-center">
                            <h4 class="red-text mb-4">Arts, Culture & Innovation</h4>
                            <p class="blue-text">We promote Malaysian culture and diversity, encouraging communities to pursue their interests in arts and culture which will drive innovation.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                <div class="drem-box rounded border box-shadow white-bg pb-4 pt-3 hover-zoom">
                    <div class="row">
                        <div class="col-sm-4 offset-sm-4 col-lg-7 offset-lg-2">
                            <img src="img/dremfund/community-01.png" class="img-fluid m-3" />
                        </div>
                        <div class="col-sm-12 text-center">
                            <h4 class="red-text mb-4">Community Well-Being</h4>
                            <p class="blue-text">We promote inclusiveness and embrace harmony by reaching out to communities in need to build a better living environment.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                <div class="drem-box rounded border box-shadow white-bg pb-4 pt-3 hover-zoom">
                    <div class="row">
                        <div class="col-sm-4 offset-sm-4 col-lg-7 offset-lg-2">
                            <img src="img/dremfund/sport-01.png" class="img-fluid m-3" />
                        </div>
                        <div class="col-sm-12 text-center">
                            <h4 class="red-text mb-4">Sports</h4>
                            <br/>
                            <p class="blue-text">We promote physical and mental well-being while fostering team spirit to build a healthier and united nation.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3 p-2 m-0">
                <div class="drem-box rounded border box-shadow white-bg pb-4 pt-3 hover-zoom">
                    <div class="row">
                        <div class="col-sm-4 offset-sm-4 col-lg-7 offset-lg-2">
                            <img src="img/dremfund/knowledge-01.png" class="img-fluid m-3" />
                        </div>
                        <div class="col-sm-12 text-center">
                            <h4 class="red-text mb-4">Knowledge Building</h4>
                            <br/>
                            <p class="blue-text">We engage in learning and educational activities to enhance knowledge and skills of the local communities.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--  end  -->

<!-- how to be   -->
<div id="howtobe" class="container-fluid white-bg pt-5 pb-5">
    <div class="container pt-4 pb-4">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="blue-text">HOW TO BE A VOLUNTEER</h1>
            </div>
        </div>
        <div class="row align-items-center mb-3">
            <div class="col-sm-12 col-md-8 pt-3 blue-text">
                <p>Volunteering and helping others can help you maintain a healthy lifestyle, expand your network, keep you mentally stimulated, and provide a sense of purpose. While it’s true that the more you volunteer, the more benefits you’ll experience, volunteering doesn’t have to involve a long-term commitment or take a huge amount of time out of your busy day. Simple ways of giving can help others or those in need and contribute towards creating a postive impact to our communitties.</p>
                <p>Come join us today and be a part of our initiatives and worthwhile causes to benefit the people in need, the community and even greater benefits for you, the volunteer.</p>
            </div>
            <div class="col-sm-4 col-md-3 d-sm-none d-md-block">
                <img src="img/logo/vmlogoblacktext.png" class="img-fluid" />
            </div>
        </div>
        <div class="row pb-3">
            <div class="col-sm-12">
                <a href="{{route('login')}}" class="btn btn-red">Register Now</a>
            </div>
        </div>
    </div>
</div>
<!--  end  -->

<!-- benefit   -->
<div id="benefit" class="container-fluid bluesea-bg pt-5 pb-5">
    <div class="container pt-4 pb-4">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="blue-text">BENEFITS OF VOLUNTEERING</h1>
            </div>
        </div>
        <div class="row align-items-center mb-3 pt-3">
            <div class="col-sm-4 col-md-12 drem-box rounded border white-bg pt-5">
                <img src="img/getinvolved/benefit.png" class="img-fluid offset-md-1" />
            </div>
        </div>
    </div>
</div>
<!--  end  -->


@endsection @section('js') @parent @endsection

resources/views/journal.blade.php
@extends('layouts.front.master') @section('content')
<!--  header image      -->
<div class="container-fluid p-0 ">
    <div class="row header-img align-items-center justify-content-center" style="background-image: url(/img/journal/background.jpg); background-position:bottom;">
        <div class="col-md-12 text-center">
            <h1 class="white-text text-shadow">THE PEOPLE'S JOURNAL</h1>
            <h5 class="white-text text-shadow">Unique, well-told stories/essays/write-ups shared by the community!</h5>
        </div>
    </div>
</div>
<!--  end  -->

<!--  featured  -->
@if($featured)
<div id="featured" class="container-fluid p-0 pink-bg pt-5 pb-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 mb-3">
                <h1 class="text-white">ARTICLE OF THE MONTH</h1>
            </div>
        </div>
        <div class="row no-gutters" style="max-height:800px; overflow:hidden">
            <div class="col-md-8">
                <img src="{{ $featured->getMedia('journals')->first()->getUrl() }}" class="img-fluid rounded-left" style="width:100%; height:100%"  />
            </div>
            <div class="col-md-4 white-bg rounded-right">
                <div class="row pb-3 pt-5 pl-4 pr-4">
                    <p class="bold blue-text">{{ Carbon\Carbon::parse($featured->createad_at)->format('F Y') }}</p>
                </div>
                <div class="row pr-4 pl-4 pb-2">
                    <h3 class="dotdotdot-title mb-3" style="overflow:hidden">{{ $featured->title }}</h3>
                </div>
                <div class="row pt-1 pr-4 pl-4 pb-3">
                    <p class="dotdotdot">{{ $featured->content }}</p>
                </div>
                <div class="row p-4">
                    <div class="col-md-12">
                        <a href="{{ route('journals.show', $featured->name) }}" class="btn btn-blue btn-block">READ STORY</a>
                    </div>
                    
                </div>
                
            </div>
        </div>
    </div>
</div>
@endif
<!--  end  -->


<!-- tpj  -->
@if(!$journals->isEmpty())
<div id="tpj" class="container-fluid gray-bg pt-5 pb-5">
    <div class="container">
        <div class="row">
            <h1 class="blue-text">THE PEOPLE'S JOURNAL</h1>
        </div>
        <div class="row p-3">
            
            <div class="slick-people-journal">
                @foreach($journals as $journal)
                <div class="pj-box col-sm-12 col-md-12 d-flex flex-wrap justify-content-center border rounded p-0 m-2 box-shadow white-bg">
                    <div class="col-sm-12 img" style="background-image: url({{ $journal->getMedia('journals')->first()->getUrl() }}); background-size: cover; background-repeat: no-repeat; background-position: center; height:200px"></div>
                    <div class="text-center" style="max-height:150px; overflow:hidden">   
                        <h5 class="font-weight-bold pt-4 pl-4 pr-4 pb-3 d-inline-block text-truncate" style="overflow:hidden;
                        min-height: 60px; max-height: 120px; max-width: 250px">{{ $journal->title }}</h5>
                        <div class="row justify-content-center mb-3"><a href="{{ route('journals.show', $journal->name) }}" class="btn btn-blue mb-2">READ STORY</a></div>
                    </div>
                    
                </div>
                @endforeach
            </div>
           
        </div>
    </div>
</div>
@endif
<!--  end  -->

{{-- Call to hantar article --}}
<div id="share" class="container-fluid white-bg pt-5 pb-5">
    <div class="container">
        <div class="row p-4 mx-2 mt-4 white-bg">
            <div class="col-md-10">
                <div class="row">
                    <div class="col-sm-1b2">
                        <h1 class="pink-text mb-4">HAVE GOOD STORIES TO SHARE?</h1>
                        <h3 class="blue-text mb-4">Submit Your Articles</h3>
                    </div>
                    <div class="col-sm-12 pr-5 pl-0 blue-text">
                        <p>The theme for this month is <span class="pink-text bold">"{{ $theme->title or ' ' }}"</span>.</p>
                        <p>We are looking for unique, well-told stories/essays/write-ups that you would like to share! We are open to receiving stories in various formats from graphic essays, photo essays, personal opinion pieces
                            to even comedic articles. There is no strict word count, but the 800 to 1200 word range would be preferable. Both Malay & English articles are accepted so submit your stories today!</p>
                        <br/>
                        
                        <p class="mb-3">What you need to do is donwload the article form then submit below</p>
                        <a href="/tpj_form.docx" download="TPJ Form" class="btn btn-pink-o m-2" style="width:160px">DOWNLOAD</a>
                        <a href="mailto:BMG@volunteermalaysia.my" target="_blank" class="btn btn-blue m-2" style="width:160px">SUBMIT</a>
                    </div>
                </div>
            </div>
            <div class="col-md-2 align-self-center">
                <img src="{{asset('img/journal/articleimage.png')}}" class="img-responsive" style="height:200px;" />
            </div>
            
        </div>
    </div>
</div>

{{-- Archive --}}
<div id="archive" class="container-fluid gray-bg pt-5 pb-5">
    <div class="container">
        <div class="row justify-content-between align-items-center">
            <h1 class="blue-text">THE PEOPLE'S JOURNAL ARCHIVE</h1>
            <a href="{{route('journal.archive')}}" class="pink-text bold mb-0">VIEW ARCHIVES <i class="fas fa-arrow-alt-circle-right"></i></a>
        </div>
        <div class="row mt-4">
            @php
            $now = Carbon\Carbon::now();
            $this_month = $now->format('n');
            if($this_month < 4){
                $month = 1;
            }else if($this_month < 7){
                $month = 4;
            }else if($this_month < 10){
                $month = 7;
            }else{
                $month = 10;
            }

            $diff_month = $this_month - $month;
            @endphp
            
            @for($i = '0'; $i < 4; $i++)   
            
            @php
                $j = $diff_month + ($i*3);
                $loop_date = Carbon\Carbon::now()->startOfMonth();
            @endphp

            <div class="col-md-3">
                <div class="journal-cont white-bg p-2 rounded">
                    <div class="row justify-content-center">
                        <div class="col-md-12 text-center py-5" style="background-color:#9BF0E1;">
                            <h1 class="blue-text m-0">
                                {{ $loop_date->subMonths($j)->format('M') }} - {{ $loop_date->addMonths(2)->format('M') }}
                                <br/>
                                {{ $loop_date->format('Y') }}
                            </h1>
                        </div>
                    </div>
                    <div class="row justify-content-center text-center">
                        <div class="col-md-12 p-4">
                            <a href="{{ route('journal.archive', ['year' => Carbon\Carbon::now()->subMonth($i)->format('Y'), 'month' => Carbon\Carbon::now()->subMonth($j)->format('n')]) }}" class="btn btn-blue">VIEW ARCHIVE</a>
                        </div>
                    </div>
                </div>
            </div>
            @endfor
        </div>
    </div>
</div>



@endsection 
@section('js') 
@parent 
<script>
    $(document).ready(function () {
        $(".dotdotdot").dotdotdot({

            ellipsis: "\u2026",
            height: 150,
            truncate: "word",

        });

         $(".dotdotdot-title-tpj").dotdotdot({

        ellipsis: "\u2026 ",
        truncate: "word",

        });

        $(".dotdotdot-title").dotdotdot({

        ellipsis: "\u2026 ",
        height: 100,
        truncate: "word",

        });
});

</script>
@endsection

resources/views/press_archive.blade.php
@extends('layouts.front.master') @section('content')
<!--  header -->
<div class="container-fluid gray-bg p-0 " style="min-height: 90vh">
    <div class="container white-bg py-5"  style="min-height: 90vh">
        <div class="row">
            <div class="col-md-12 pl-4 pr-4 pb-3 pt-3">
                <h1 class="blue-text">PRESS RELEASE ARCHIVE</h1>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-3 d-flex align-items-center">
                <input id="search" type="text" class="form-control mr-1" placeholder="Enter text to search..." /><i class="fas fa-search"></i>
            </div>
            <div class="col-md-3">
                @php
                $now = Carbon\Carbon::now()->year;
                $last = 2014;
                @endphp
                <select id="year_select" class="form-control" title="Filter by year">
                    @for ($i = $now; $i >= $last; $i--)
                    <option value="{{ $i }}">{{ $i }}</option>
                    @endfor
                </select>
            </div>
        </div>

        {{-- Archive listing --}}
        
        <div id="data_listing" class="row mt-5 px-3">
            
        </div>

    </div>
    
</div>
<!--  end  -->

@endsection 
@section('js') 
@parent

<script>

    $( document ).ready(function() {
        call_ajax({{ Carbon\Carbon::now()->year }});
    });

    $('#year_select').on('change', function() {
        call_ajax(this.value);
    });  

    $("#search").keyup(function() {
        var value = this.value.toLowerCase();

        $("#data_listing").find("a").each(function(index) {
            
            //if (!index) return;
            var item = $(this).find(".bold").first().text();
            $(this).toggle(item.toLowerCase().indexOf(value) !== -1);
        });
    });

    function call_ajax(year){
        
        $.ajax({
            type:'GET',
            url:'/presses/year/'+year,
            success:function(data){
                append_archive(data);
            }
        });
    }  

    function append_archive(data){
        $('#data_listing').empty();
        $('#search').val('');

        data.forEach(data => {
            $("#data_listing").append(`
            <a href="`+data['link']+`" target="_blank" style="width:100%">
                <div class="col-md-12 border-bottom p-3 tpj-list">
                    <p class="mb-0">`+data['released_at']+`</p>
                    <p class="bold mb-0">`+data['title']+`</p>
                </div>
            </a>
            `);
        });
    }
</script>

@endsection