routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/send/{project}', 'HomeController@send')->name('send');
Route::get('/test', 'HomeController@test')->name('test');

Route::get('/about', 'HomeController@about')->name('about');
Route::get('/dreamfund', 'HomeController@dreamfund')->name('dreamfund');
Route::get('/happening', 'HomeController@happening')->name('happening');
Route::get('/media', 'HomeController@media')->name('media');
Route::get('/photos', 'HomeController@photos')->name('photos');
Route::get('/videos', 'HomeController@videos')->name('videos');
Route::any('/explore', 'ProjectController@explore')->name('explore');
Route::any('/journal', 'HomeController@journal')->name('journal');
Route::any('/journal/archive/{year?}/{month?}', 'HomeController@journal_archive')->name('journal.archive');
Route::any('/journal/detail', 'HomeController@journal_detail')->name('journal.detail');

Route::get('/journal/year/{year?}/{month?}', 'JournalController@list');

Route::any('/media/press', 'HomeController@media_press')->name('media.press');
Route::get('/presses/year/{year?}', 'PressController@list');

Route::resource('themes', 'JournalThemeController');

Route::any('/contactus', 'HomeController@contactus')->name('contactus');
Route::any('/partnership', 'HomeController@partnership')->name('partnership');
Route::any('/getinvolved', 'HomeController@getinvolved')->name('getinvolved');

Route::get('/verify/{code}', 'HomeController@verify')->name('verify');
Route::get('/sms/verify', 'HomeController@verify_sms')->name('sms.confirm');
Route::get('/sms/resend', 'HomeController@resend_code')->name('sms.resend');
Route::post('/sms/confirm', 'HomeController@confirm_sms')->name('sms.confirm.code');
Route::get('/email/resend', 'HomeController@resend_email')->name('email.resend');
Route::get('/email/test/{project}', 'HomeController@email_test')->name('email.test');



//facebook auth
Route::get('auth/facebook', 'Auth\FacebookController@redirectToFacebook');
Route::get('auth/facebook/callback', 'Auth\FacebookController@handleFacebookCallback');

//google auth
Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/fill', 'HomeController@fill')->name('fill');
    Route::post('/auth/update', 'HomeController@auth_update')->name('auth.update');
    Route::post('/phone/update', 'HomeController@phone_update')->name('phone.update');
    Route::get('/phone/change', 'HomeController@phone_change')->name('phone.change');
});

Route::group( ['middleware' => ['auth', 'checkAccount']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');

    Route::get('/projects/me',  'ProjectController@index_me')->name('projects.me');
    Route::get('/projects/joined',  'ProjectController@index_joined')->name('projects.joined');

    Route::get('/profile',  'ProfileController@profile')->name('profile');
    Route::get('/profile/edit',  'ProfileController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'ProfileController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'ProfileController@profile_update')->name('profile.update');
    Route::put('/account/update',  'ProfileController@account_update')->name('account.update');
    Route::put('/profile/password/update',  'ProfileController@profile_pw_update')->name('profile.pw_update');
    Route::put('/profile/disaster',  'ProfileController@profile_disaster')->name('profile.disaster');
    Route::put('/profile/update/categories', 'ProfileController@update_categories')->name('profile.update.categories');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('projects', 'ProjectController');

    Route::resource('presses', 'PressController');
    Route::get('/presses/{id}/restore', 'PressController@restore')->name('presses.restore');
    Route::put('/presses/{id}/banner', 'PressController@image_update')->name('presses.image.update');
    Route::delete('/presses/{id}/banner', 'PressController@image_delete')->name('presses.image.delete');

    Route::get('/projects/{project}/status/{status}', 'ProjectController@update_status')->name('projects.update.status');

    Route::get('/projects/join/{project}', 'ProjectController@join_project')->name('projects.join');
    Route::get('/projects/leave/{project}', 'ProjectController@leave_project')->name('projects.leave');

    Route::get('/projects/subscribe/{project}', 'ProjectController@subscribe_project')->name('projects.subscribe');
    Route::get('/projects/unsubscribe/{project}', 'ProjectController@unsubscribe_project')->name('projects.unsubscribe');

    Route::put('/projects/update/{project}/detail', 'ProjectController@update_detail')->name('projects.update.detail');
    Route::put('/projects/update/{project}/location', 'ProjectController@update_location')->name('projects.update.location');
    Route::put('/projects/update/{project}/volunteer', 'ProjectController@update_volunteer')->name('projects.update.volunteer');
    Route::put('/projects/update/{project}/categories', 'ProjectController@update_categories')->name('projects.update.categories');
    Route::put('/projects/update/{project}/type', 'ProjectController@update_type')->name('projects.update.type');


    //cms
    Route::resource('banners', 'BannerController');
    Route::get('/banners/{id}/restore', 'BannerController@restore')->name('banners.restore');

    Route::resource('journals', 'JournalController')->except([
        'show'
    ]);

    Route::get('/journals/{id}/restore', 'JournalController@restore')->name('journals.restore');
    Route::put('/journals/{id}/banner/main/image', 'JournalController@journal_main_image_update')->name('journals.main.image.update');
    Route::put('/journals/{id}/banner/author/image', 'JournalController@journal_author_image_update')->name('journals.author.image.update');

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser')->name('datatables.users');
    Route::get('datatables/getCategories', 'DatatablesController@getCategories')->name('datatables.categories');
    Route::get('datatables/getProjects', 'DatatablesController@getProjects')->name('datatables.projects');
    Route::get('datatables/getPress', 'DatatablesController@getPresses')->name('datatables.presses');
    Route::get('datatables/getMyProjects', 'DatatablesController@getMyProjects')->name('datatables.projects.me');
    Route::get('datatables/getMyJoinedProjects', 'DatatablesController@getMyJoinedProjects')->name('datatables.projects.joined');
    Route::get('datatables/getJoined/{project}', 'DatatablesController@getJoined')->name('datatables.joined');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');


});

Route::resource('projects', 'ProjectController')->only([
    'show'
]);

Route::resource('journals', 'JournalController')->only([
    'show'
]);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

// use App\Authorizable;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    // use Authorizable;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $result = Post::latest()->with('user')->paginate();
        return view('post.index', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:10',
            'body' => 'required|min:20'
        ]);

        $request->user()->posts()->create($request->all());

        flash('Post has been added');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $post = Post::findOrFail($post->id);

        return view('post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request, [
            'title' => 'required|min:10',
            'body' => 'required|min:20'
        ]);

        $me = $request->user();

        if( $me->hasRole('Admin') ) {
            $post = Post::findOrFail($post->id);
        } else {
            $post = $me->posts()->findOrFail($post->id);
        }

        $post->update($request->all());

        flash()->success('Post has been updated.');

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $me = Auth::user();

        if( $me->hasRole('Admin') ) {
            $post = Post::findOrFail($post->id);
        } else {
            $post = $me->posts()->findOrFail($post->id);
        }

        $post->delete();

        flash()->success('Post has been deleted.');

        return redirect()->route('posts.index');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.master')

@section('title', 'Posts')
@section('subtitle', '| Create New Post')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

        <h1>Create New Post</h1>
        <hr>

    {{-- Using the Laravel HTML Form Collective to create our form --}}
        {{ Form::open(array('route' => 'posts.store')) }}

        <div class="form-group">
            {{ Form::label('title', 'Title') }}
            {{ Form::text('title', null, array('class' => 'form-control')) }}
            <br>

            {{ Form::label('body', 'Post Body') }}
            {{ Form::textarea('body', null, array('class' => 'form-control')) }}
            <br>

            {{ Form::submit('Create Post', array('class' => 'btn btn-success btn-lg btn-block')) }}
            {{ Form::close() }}
        </div>
        </div>
    </div>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.master')

@section('title', 'Posts')
@section('subtitle', '| Edit Post')

@section('content')
<div class="row">

    <div class="col-md-8 col-md-offset-2">

        <h1>Edit Post</h1>
        <hr>
            {{ Form::model($post, array('route' => array('posts.update', $post->id), 'method' => 'PUT')) }}
            <div class="form-group">
            {{ Form::label('title', 'Title') }}
            {{ Form::text('title', null, array('class' => 'form-control')) }}<br>

            {{ Form::label('body', 'Post Body') }}
            {{ Form::textarea('body', null, array('class' => 'form-control')) }}<br>

            {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}

            {{ Form::close() }}
    </div>
    </div>
</div>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.master')

@section('title', 'Posts')

@section('content')

    <div class="row bg-white has-shadow">
        <!-- Item -->
        <a class="btn btn-primary" href="posts/create">Create</a>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Page {{ $posts->currentPage() }} of {{ $posts->lastPage() }}</div>
                    @foreach ($posts as $post)
                        <div class="panel-body">
                            <li style="list-style-type:disc">
                                <a href="{{ route('posts.show', $post->id ) }}"><b>{{ $post->title }}</b><br>
                                    <p class="teaser">
                                       {{  str_limit($post->body, 100) }} {{-- Limit teaser to 100 characters --}}
                                    </p>
                                </a>
                            </li>
                        </div>
                    @endforeach
                    </div>
                    <div class="text-center">
                        {!! $posts->links() !!}
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.master')

@section('title', 'Posts')
@section('subtitle', '| View Post')

@section('content')

<div class="container">

    <h1>{{ $post->title }}</h1>
    <hr>
    <p class="lead">{{ $post->body }} </p>
    <hr>
    {!! Form::open(['method' => 'DELETE', 'route' => ['posts.destroy', $post->id] ]) !!}
    <a href="{{ url()->previous() }}" class="btn btn-primary">Back</a>
    @can('Edit Post')
    <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-info" role="button">Edit</a>
    @endcan
    @can('Delete Post')
    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
    @endcan
    {!! Form::close() !!}

</div>

@endsection