routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/send/{project}', 'HomeController@send')->name('send');
Route::get('/test', 'HomeController@test')->name('test');

Route::get('/about', 'HomeController@about')->name('about');
Route::get('/dreamfund', 'HomeController@dreamfund')->name('dreamfund');
Route::get('/happening', 'HomeController@happening')->name('happening');
Route::get('/media', 'HomeController@media')->name('media');
Route::get('/photos', 'HomeController@photos')->name('photos');
Route::get('/videos', 'HomeController@videos')->name('videos');
Route::any('/explore', 'ProjectController@explore')->name('explore');
Route::any('/journal', 'HomeController@journal')->name('journal');
Route::any('/journal/archive/{year?}/{month?}', 'HomeController@journal_archive')->name('journal.archive');
Route::any('/journal/detail', 'HomeController@journal_detail')->name('journal.detail');

Route::get('/journal/year/{year?}/{month?}', 'JournalController@list');

Route::any('/media/press', 'HomeController@media_press')->name('media.press');
Route::get('/presses/year/{year?}', 'PressController@list');

Route::resource('themes', 'JournalThemeController');

Route::any('/contactus', 'HomeController@contactus')->name('contactus');
Route::any('/partnership', 'HomeController@partnership')->name('partnership');
Route::any('/getinvolved', 'HomeController@getinvolved')->name('getinvolved');

Route::get('/verify/{code}', 'HomeController@verify')->name('verify');
Route::get('/sms/verify', 'HomeController@verify_sms')->name('sms.confirm');
Route::get('/sms/resend', 'HomeController@resend_code')->name('sms.resend');
Route::post('/sms/confirm', 'HomeController@confirm_sms')->name('sms.confirm.code');
Route::get('/email/resend', 'HomeController@resend_email')->name('email.resend');
Route::get('/email/test/{project}', 'HomeController@email_test')->name('email.test');



//facebook auth
Route::get('auth/facebook', 'Auth\FacebookController@redirectToFacebook');
Route::get('auth/facebook/callback', 'Auth\FacebookController@handleFacebookCallback');

//google auth
Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/fill', 'HomeController@fill')->name('fill');
    Route::post('/auth/update', 'HomeController@auth_update')->name('auth.update');
    Route::post('/phone/update', 'HomeController@phone_update')->name('phone.update');
    Route::get('/phone/change', 'HomeController@phone_change')->name('phone.change');
});

Route::group( ['middleware' => ['auth', 'checkAccount']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');

    Route::get('/projects/me',  'ProjectController@index_me')->name('projects.me');
    Route::get('/projects/joined',  'ProjectController@index_joined')->name('projects.joined');

    Route::get('/profile',  'ProfileController@profile')->name('profile');
    Route::get('/profile/edit',  'ProfileController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'ProfileController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'ProfileController@profile_update')->name('profile.update');
    Route::put('/account/update',  'ProfileController@account_update')->name('account.update');
    Route::put('/profile/password/update',  'ProfileController@profile_pw_update')->name('profile.pw_update');
    Route::put('/profile/disaster',  'ProfileController@profile_disaster')->name('profile.disaster');
    Route::put('/profile/update/categories', 'ProfileController@update_categories')->name('profile.update.categories');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('projects', 'ProjectController');

    Route::resource('presses', 'PressController');
    Route::get('/presses/{id}/restore', 'PressController@restore')->name('presses.restore');
    Route::put('/presses/{id}/banner', 'PressController@image_update')->name('presses.image.update');
    Route::delete('/presses/{id}/banner', 'PressController@image_delete')->name('presses.image.delete');

    Route::get('/projects/{project}/status/{status}', 'ProjectController@update_status')->name('projects.update.status');

    Route::get('/projects/join/{project}', 'ProjectController@join_project')->name('projects.join');
    Route::get('/projects/leave/{project}', 'ProjectController@leave_project')->name('projects.leave');

    Route::get('/projects/subscribe/{project}', 'ProjectController@subscribe_project')->name('projects.subscribe');
    Route::get('/projects/unsubscribe/{project}', 'ProjectController@unsubscribe_project')->name('projects.unsubscribe');

    Route::put('/projects/update/{project}/detail', 'ProjectController@update_detail')->name('projects.update.detail');
    Route::put('/projects/update/{project}/location', 'ProjectController@update_location')->name('projects.update.location');
    Route::put('/projects/update/{project}/volunteer', 'ProjectController@update_volunteer')->name('projects.update.volunteer');
    Route::put('/projects/update/{project}/categories', 'ProjectController@update_categories')->name('projects.update.categories');
    Route::put('/projects/update/{project}/type', 'ProjectController@update_type')->name('projects.update.type');


    //cms
    Route::resource('banners', 'BannerController');
    Route::get('/banners/{id}/restore', 'BannerController@restore')->name('banners.restore');

    Route::resource('journals', 'JournalController')->except([
        'show'
    ]);

    Route::get('/journals/{id}/restore', 'JournalController@restore')->name('journals.restore');
    Route::put('/journals/{id}/banner/main/image', 'JournalController@journal_main_image_update')->name('journals.main.image.update');
    Route::put('/journals/{id}/banner/author/image', 'JournalController@journal_author_image_update')->name('journals.author.image.update');

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser')->name('datatables.users');
    Route::get('datatables/getCategories', 'DatatablesController@getCategories')->name('datatables.categories');
    Route::get('datatables/getProjects', 'DatatablesController@getProjects')->name('datatables.projects');
    Route::get('datatables/getPress', 'DatatablesController@getPresses')->name('datatables.presses');
    Route::get('datatables/getMyProjects', 'DatatablesController@getMyProjects')->name('datatables.projects.me');
    Route::get('datatables/getMyJoinedProjects', 'DatatablesController@getMyJoinedProjects')->name('datatables.projects.joined');
    Route::get('datatables/getJoined/{project}', 'DatatablesController@getJoined')->name('datatables.joined');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');


});

Route::resource('projects', 'ProjectController')->only([
    'show'
]);

Route::resource('journals', 'JournalController')->only([
    'show'
]);

resources/views/layouts/basic/content.blade.php
@include('flash::message')
{{-- @include('shared/_error') --}}
@yield('content')

resources/views/layouts/basic/footer.blade.php
<!-- Footer -->
<footer class="py-5 bg-dark footer">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Hadiantech 2018</p>
  </div>
  <!-- /.container -->
</footer>

resources/views/layouts/basic/master.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/journal/bootstrap.min.css" rel="stylesheet" integrity="sha384-/qQob+A1P2FeRYphuSbqp7heEKdhjZxqgAz/yWLX9CQKU9FTB8wKTexI0IiFlIXC" crossorigin="anonymous">
      
    <link href="{!! asset('css/basic_bootstrap.css') !!}" media="all" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    @yield('css')

  </head>

  <body>

    @include('cookieConsent::index')

    @include('layouts.basic.navbar')
    <!-- Page Content -->
  
    @include('layouts.basic.content')
    @include('shared._popup')

    <!-- /.container -->
    @include('layouts.basic.footer')


    @include('shared._delete_confirm')

    <script src="{{ mix('/js/app.js') }}"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

    @yield('js')

  </body>

</html>

resources/views/layouts/basic/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light white-bg">
    <a class="navbar-brand p-0 m-0" href="/"><img src="{{asset('img/logo/vmlogotext.png')}}" width="auto" height="35" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="color: #000;"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <div class="item d-lg-flex">
                <a class="" href="{{route('about')}}">
                    <div class="nav-item nav-link blue4-text mx-lg-2" href="" style="position: relative; display: inline-block;">ABOUT US
                        <i class="fas fa-sort-down" style="position: absolute; right:-4px; top:14px; display: inline-block;"></i>
                        <div class="sub-menu white-bg rounded px-1 pt-3 pb-3">
                            <a class="nav-link blue4-text" href="{{route('about')}}#vision_mission">Vision & Mission</a>
                            <a class="nav-link blue4-text" href="{{route('about')}}#pillars">Our Pillars</a>
                   <!--         <a class="nav-link blue4-text" href="{{route('about')}}#team">Management Team</a> -->
                        </div>
                    </div>
                </a>

                <a class="" href="{{route('getinvolved')}}">
                    <div class="nav-item nav-link blue4-text mx-lg-3" href="" style="position: relative; display: inline-block;">GET INVOLVED
                        <i class="fas fa-sort-down" style="position: absolute; right:-4px; top:14px; display: inline-block;"></i>
                        <div class="sub-menu white-bg rounded px-1 pt-3 pb-3">
                            <a class="nav-link blue4-text" href="{{route('getinvolved')}}#whyvolunteer">Volunteer With Us</a>
                            <a class="nav-link blue4-text" href="{{route('getinvolved')}}#howtobe">Be A Volunteer</a>
                            <a class="nav-link blue4-text" href="{{route('getinvolved')}}#benefit">Benefits Of Volunteering</a>
                        </div>
                    </div>
                </a> 
                
                <a class="" href="{{route('explore')}}">
                    <div class="nav-item nav-link blue4-text mx-lg-2" href="" style="position: relative; display: inline-block;">PROJECTS & EVENTS
                        <i class="fas fa-sort-down" style="position: absolute; right:-4px; top:14px; display: inline-block;"></i>
                        <div class="sub-menu white-bg rounded px-1 pt-3 pb-3">
                            <a class="nav-link blue4-text" href="{{route('explore')}}#recentproject">Current Projects</a>
                            <a class="nav-link blue4-text" href="{{route('explore')}}#stories">Success Stories</a>
                            <a class="nav-link blue4-text" href="{{route('explore')}}#collaborate">Collaborate With Us</a>
                            <a class="nav-link blue4-text" href="{{route('explore')}}#partners">Our Partners</a>
                            <a class="nav-link blue4-text" href="{{route('explore')}}#projecthighlight">Projects Highlights</a>
                        </div>
                    </div>
                </a>

                <a class="" href="{{route('dreamfund')}}">
                    <div class="nav-item nav-link blue4-text mx-lg-3" href="" style="position: relative; display: inline-block;">DREAM FUND
                        <i class="fas fa-sort-down" style="position: absolute; right:-4px; top:14px; display: inline-block;"></i>
                        <div class="sub-menu white-bg rounded px-1 pt-3 pb-3">
                            <a class="nav-link blue4-text" href="{{route('dreamfund')}}#whatis">What is DREAM Fund</a>
                            <a class="nav-link blue4-text" href="{{route('dreamfund')}}#apply">Apply For DREAM Fund</a>
                            <a class="nav-link blue4-text" href="{{route('dreamfund')}}#projects">Project Examples</a>
                        </div>
                    </div>
                </a>

                <a class="" href="{{route('journal')}}">
                    <div class="nav-item nav-link nav-item-fix blue4-text mx-lg-3" href="" style="position: relative; display: inline-block; margin-bottom:5px;">THE PEOPLE'S JOURNAL
                    <i class="fas fa-sort-down" style="position: absolute; right:-4px; top:14px; display: inline-block;"></i>
                        <div class="sub-menu white-bg rounded px-1 pt-3 pb-3">
                            <a class="nav-link blue4-text" href="{{route('journal')}}#featured">Article of The Month</a>
                            <a class="nav-link blue4-text" href="{{route('journal')}}#share">Share Your Stories</a>
                            <a class="nav-link blue4-text" href="{{route('journal')}}#archive">Archives</a>
                    </div>
                    </div>
                </a> 

                <a class="" href="{{route('media')}}">
                    <div class="nav-item nav-link blue4-text mx-lg-3" href="" style="position: relative; display: inline-block;">MEDIA CENTRE
                        <i class="fas fa-sort-down" style="position: absolute; right:-4px; top:14px; display: inline-block;"></i>
                        <div class="sub-menu white-bg rounded px-1 pt-3 pb-3">
                            <a class="nav-link blue4-text" href="{{route('media')}}#press">Press Release</a>
                            <a class="nav-link blue4-text" href="{{route('media')}}#factsheet">Factsheet</a>
                            <a class="nav-link blue4-text" href="{{route('media')}}#faq">FAQ</a>
                            <a class="nav-link blue4-text" href="{{route('media.press')}}">Archives</a>
                            <a class="nav-link blue4-text" href="{{route('media')}}">Photo Gallery</a>
                        </div>
                    </div>
                </a> 

                <a class="" href="{{route('contactus')}}">
                    <div class="nav-item nav-link blue4-text mx-lg-3 nav-item-fix" href="" style="position: relative; display: inline-block;">CONTACT US
                    </div>
                </a> 

                @guest
                @else
                <a class="" href="{{ route('projects.create') }}">
                    <div class="nav-item nav-link blue4-text mx-lg-3 nav-item-fix" href="" style="position: relative; display: inline-block;">CREATE PROJECT</div>
                </a>
                @endguest

                @guest
                <a class="nav-item nav-link blue4-text mx-lg-2 nav-item-fix" href="{{route('login')}}" style="position: relative; display: inline-block;">SIGN IN</a> 
                @else

                @include('layouts.basic.user_menu')

                @endguest

            </div>
            <div class="item">

            </div>
        </div>
    </div>
</nav>

resources/views/layouts/basic/sidebar.blade.php
<!-- sidebar -->
<div class="d-flex">
    <nav class="sidebar bg-dark">
        <ul class="list-unstyled">
            <li><a href="#"><i class="fa fa-fw fa-link"></i> Dashboard</a></li>
            <li style="position: relative;">
                <a href="#submenu1" data-toggle="collapse"><i class="fa fa-fw fa-users"></i> User Management</a>
                <i class="fas fa-angle-down white-text" style="position: absolute; top:16px; right: 15px "></i>
                <ul id="submenu1" class="list-unstyled collapse">
                    <li><a href="vms_user_list.html">All User</a></li>
                    <li><a href="#">Create New User</a></li>
                </ul>
            </li>
            <li style="position: relative;">
                <a href="#submenu2" data-toggle="collapse"><i class="fa fa-fw fa-clipboard-check"></i> Project Management</a>
                <i class="fas fa-angle-down white-text" style="position: absolute; top:16px; right: 15px "></i>
                <ul id="submenu2" class="list-unstyled collapse">
                    <li><a href="vms_project_list.html">Published</a></li>
                    <li><a href="vms_project_pending.html">Pending <span class="badge badge-warning">10</span></a></li>
                    <li><a href="#">Suspended</a></li>
                    <li><a href="#">Ended</a></li>
                    <li><a href="#">Organisation</a></li>
                </ul>
            </li>

            <li><a href="#"><i class="fas fa-wrench"></i> Settings</a></li>

        </ul>
    </nav>

    <!-- REMINDER: PUT CONTENT INSIDE THIS DIV "content"  -->
</div>
<!-- end   -->

resources/views/layouts/basic/user_menu.blade.php
<div class="navbar-collapse collapse">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                @if(!Auth::user()->getMedia('profile')->first())
                <div class="user-thumbnail" style="background-image:url('{{ asset('img/default_user.png') }}')" /></div>
                @else
                <div class="user-thumbnail" style="background-image:url('{{ Auth::user()->getFirstMediaUrl('profile') }}')" /></div>
                @endif
            </a>
            <div class="dropdown-menu white-bg  dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item pb-2 pt-2" href="{{ route('profile') }}">My Profile</a>

                <a class="dropdown-item pb-2 pt-2" href="{{ route('projects.me') }}">My Project</a>

                <a class="dropdown-item pb-2 pt-2" href="{{ route('projects.joined') }}">My Joined Project</a>

                <!--
                @can('view_dashboard')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('dashboard') }}">Dashboard</a>
                @endcan
                -->

                @can('view_projects')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('projects.index') }}">Project Management</a>
                @endcan

                @can('view_users')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('users.index') }}">User Management</a>
                @endcan

                @can('view_categories')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('categories.index') }}">Category Management</a>
                @endcan

                @can('view_roles')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('roles.index') }}">Role Management</a>
                @endcan

                @can('view_banners')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('banners.index') }}">Banner Management</a>
                @endcan

                @can('view_journals')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('journals.index') }}">Journal Management</a>
                @endcan

                @can('view_presses')
                <a class="dropdown-item pb-2 pt-2" href="{{ route('presses.index') }}">Press Management</a>
                @endcan

                <a class="dropdown-item pb-2 pt-2" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
            </div>
        </li>
    </ul>
</div>

<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>