routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/send/{project}', 'HomeController@send')->name('send');
Route::get('/test', 'HomeController@test')->name('test');

Route::get('/about', 'HomeController@about')->name('about');
Route::get('/dreamfund', 'HomeController@dreamfund')->name('dreamfund');
Route::get('/happening', 'HomeController@happening')->name('happening');
Route::get('/media', 'HomeController@media')->name('media');
Route::get('/photos', 'HomeController@photos')->name('photos');
Route::get('/videos', 'HomeController@videos')->name('videos');
Route::any('/explore', 'ProjectController@explore')->name('explore');
Route::any('/journal', 'HomeController@journal')->name('journal');
Route::any('/journal/archive/{year?}/{month?}', 'HomeController@journal_archive')->name('journal.archive');
Route::any('/journal/detail', 'HomeController@journal_detail')->name('journal.detail');

Route::get('/journal/year/{year?}/{month?}', 'JournalController@list');

Route::any('/media/press', 'HomeController@media_press')->name('media.press');
Route::get('/presses/year/{year?}', 'PressController@list');

Route::resource('themes', 'JournalThemeController');

Route::any('/contactus', 'HomeController@contactus')->name('contactus');
Route::any('/partnership', 'HomeController@partnership')->name('partnership');
Route::any('/getinvolved', 'HomeController@getinvolved')->name('getinvolved');

Route::get('/verify/{code}', 'HomeController@verify')->name('verify');
Route::get('/sms/verify', 'HomeController@verify_sms')->name('sms.confirm');
Route::get('/sms/resend', 'HomeController@resend_code')->name('sms.resend');
Route::post('/sms/confirm', 'HomeController@confirm_sms')->name('sms.confirm.code');
Route::get('/email/resend', 'HomeController@resend_email')->name('email.resend');
Route::get('/email/test/{project}', 'HomeController@email_test')->name('email.test');



//facebook auth
Route::get('auth/facebook', 'Auth\FacebookController@redirectToFacebook');
Route::get('auth/facebook/callback', 'Auth\FacebookController@handleFacebookCallback');

//google auth
Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::group( ['middleware' => ['auth']], function() {
    Route::get('/fill', 'HomeController@fill')->name('fill');
    Route::post('/auth/update', 'HomeController@auth_update')->name('auth.update');
    Route::post('/phone/update', 'HomeController@phone_update')->name('phone.update');
    Route::get('/phone/change', 'HomeController@phone_change')->name('phone.change');
});

Route::group( ['middleware' => ['auth', 'checkAccount']], function() {
    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');

    Route::get('/projects/me',  'ProjectController@index_me')->name('projects.me');
    Route::get('/projects/joined',  'ProjectController@index_joined')->name('projects.joined');

    Route::get('/profile',  'ProfileController@profile')->name('profile');
    Route::get('/profile/edit',  'ProfileController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'ProfileController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'ProfileController@profile_update')->name('profile.update');
    Route::put('/account/update',  'ProfileController@account_update')->name('account.update');
    Route::put('/profile/password/update',  'ProfileController@profile_pw_update')->name('profile.pw_update');
    Route::put('/profile/disaster',  'ProfileController@profile_disaster')->name('profile.disaster');
    Route::put('/profile/update/categories', 'ProfileController@update_categories')->name('profile.update.categories');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('projects', 'ProjectController');

    Route::resource('presses', 'PressController');
    Route::get('/presses/{id}/restore', 'PressController@restore')->name('presses.restore');
    Route::put('/presses/{id}/banner', 'PressController@image_update')->name('presses.image.update');
    Route::delete('/presses/{id}/banner', 'PressController@image_delete')->name('presses.image.delete');

    Route::get('/projects/{project}/status/{status}', 'ProjectController@update_status')->name('projects.update.status');

    Route::get('/projects/join/{project}', 'ProjectController@join_project')->name('projects.join');
    Route::get('/projects/leave/{project}', 'ProjectController@leave_project')->name('projects.leave');

    Route::get('/projects/subscribe/{project}', 'ProjectController@subscribe_project')->name('projects.subscribe');
    Route::get('/projects/unsubscribe/{project}', 'ProjectController@unsubscribe_project')->name('projects.unsubscribe');

    Route::put('/projects/update/{project}/detail', 'ProjectController@update_detail')->name('projects.update.detail');
    Route::put('/projects/update/{project}/location', 'ProjectController@update_location')->name('projects.update.location');
    Route::put('/projects/update/{project}/volunteer', 'ProjectController@update_volunteer')->name('projects.update.volunteer');
    Route::put('/projects/update/{project}/categories', 'ProjectController@update_categories')->name('projects.update.categories');
    Route::put('/projects/update/{project}/type', 'ProjectController@update_type')->name('projects.update.type');


    //cms
    Route::resource('banners', 'BannerController');
    Route::get('/banners/{id}/restore', 'BannerController@restore')->name('banners.restore');

    Route::resource('journals', 'JournalController')->except([
        'show'
    ]);

    Route::get('/journals/{id}/restore', 'JournalController@restore')->name('journals.restore');
    Route::put('/journals/{id}/banner/main/image', 'JournalController@journal_main_image_update')->name('journals.main.image.update');
    Route::put('/journals/{id}/banner/author/image', 'JournalController@journal_author_image_update')->name('journals.author.image.update');

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser')->name('datatables.users');
    Route::get('datatables/getCategories', 'DatatablesController@getCategories')->name('datatables.categories');
    Route::get('datatables/getProjects', 'DatatablesController@getProjects')->name('datatables.projects');
    Route::get('datatables/getPress', 'DatatablesController@getPresses')->name('datatables.presses');
    Route::get('datatables/getMyProjects', 'DatatablesController@getMyProjects')->name('datatables.projects.me');
    Route::get('datatables/getMyJoinedProjects', 'DatatablesController@getMyJoinedProjects')->name('datatables.projects.joined');
    Route::get('datatables/getJoined/{project}', 'DatatablesController@getJoined')->name('datatables.joined');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');


});

Route::resource('projects', 'ProjectController')->only([
    'show'
]);

Route::resource('journals', 'JournalController')->only([
    'show'
]);

app/Journal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes; //for soft delete

use Spatie\Activitylog\Traits\LogsActivity; //for log

use Spatie\MediaLibrary\HasMedia\HasMediaTrait; //for image
use Spatie\MediaLibrary\HasMedia\HasMedia; //for image

use Carbon\Carbon;


class Journal extends Model implements HasMedia //for image
{
    use LogsActivity; //for log
    use SoftDeletes; //for soft delete
    use HasMediaTrait; //for image

    protected $dates = ['deleted_at']; //for soft delete
    protected $guarded = []; //allow all request accepted
    protected static $logFillable = true; //for log

    public function scopeCurrent($query){
        return $query->whereBetween('released_at', [Carbon::today()->startOfMonth(), Carbon::today()]);
    }
    
    public function scopeShow($query){
        return $query->where('hidden', 0);
    }

    public function scopeFeatured($query){
        return $query->where('featured', 1);
    }

    public function scopeArchive($query){
        return $query->where('released_at', '<', Carbon::today()->startOfMonth());
    }

}

app/Http/Controllers/JournalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Journal;
use SEO;
use DB;

class JournalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request('view')=='trash'){
            $journals = Journal::onlyTrashed()->get();
        }else{
            $journals = Journal::get();
        }
        return view('journals.index', compact('journals'));
    }

    public function list($year=null, $month=null){
        $journal = new Journal;
        if($year){
            $journal = $journal->whereYear('released_at', $year);
        }
        if($month){
            $j = 1;
            $months = [];
            for($i=$month;;$i++){
                array_push($months, $i);
                if($j==3){
                    break;
                }
                $j++;
            }

            $journal = $journal->whereIn(DB::raw('MONTH(released_at)'), $months);
        }
        // return $months;
        return $journal->show()->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('journals.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image'=>'required|image',
            'author_image'=>'required|image',
            'title' =>'required',
            'name' =>array(
                'required',
                'regex:/(^([a-zA-Z]+)(\d+)?$)/u',
                'unique:journals,name'
            ),
            'author_name' =>'required',
            'author_detail' =>'required',
            'content' =>'required',
            'released_at' =>'required',
            ]
        );

        $journal = Journal::create($request->only('title','name','author_name','author_detail','content', 'featured', 'hidden', 'released_at'));
        $journal->addMediaFromRequest('image')->toMediaCollection('journals');
        $journal->addMediaFromRequest('author_image')->toMediaCollection('authors');

        flash('Journal added');
        return redirect()->route('journals.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($name)
    {
        $journal = Journal::where('name', $name)->first();
        if(!$journal){
            $journal = Journal::find($name);
        }

        SEO::setTitle(config('app.name'). ' | ' .$journal->title);
        SEO::setDescription($journal->content);
        SEO::opengraph()->setUrl(route('journals.show', $journal->name));
        SEO::opengraph()->addProperty('type', 'articles');
        SEO::opengraph()->addImage($journal->getMedia('journals')->first()->getFullUrl());

        return view('journals.show', compact('journal'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Journal $journal)
    {
        return view('journals.edit', compact('journal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' =>'required',
            'name' =>array(
                'required',
                'regex:/(^([a-zA-Z]+)(\d+)?$)/u',
                'unique:journals,name,'.$id
            ),
            'author_name' =>'required',
            'author_detail' =>'required',
            'content' =>'required',
            'released_at' =>'required',
        ]);

        $journal = Journal::findOrFail($id);
        $journal->title = $request->input('title');
        $journal->name = $request->input('name');
        $journal->author_name = $request->input('author_name');
        $journal->author_detail = $request->input('author_detail');
        $journal->content = $request->input('content');
        $journal->featured = $request->input('featured');
        $journal->hidden = $request->input('hidden');
        $journal->released_at = $request->input('released_at');
        
        if($journal->isDirty('featured')){
            if($journal->featured == 1){
                Journal::where('featured', 1)
                ->update(['featured' => 0]);
            }
        }
        
        $journal->save();

        flash('Journal updated');
        return redirect()->route('journals.edit', $journal->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $journal = Journal::withTrashed()
                ->where('id', $id)->first();

        if($journal->trashed()) {
            $journal->forceDelete();
        }else{
            $journal->delete();
        }

        flash('Journal successfully deleted');
        return redirect()->route('journals.index');
    }

    public function restore($id)
    {
        $journal = Journal::withTrashed()
                    ->where('id', $id)
                    ->restore();

        flash('Journal successfully restored');
        return redirect()->route('journals.index');
    }

    public function journal_author_image_update(Request $request, $id){

        $this->validate($request, [
            'author_image'=>'required|image'
            ]
        );

        $journal = Journal::findOrFail($id);
        $journal->clearMediaCollection('authors');
        $journal->addMediaFromRequest('author_image')->toMediaCollection('authors');
        flash('Journal author image updated');
        return redirect()->route('journals.edit',$journal->id);

    }

    public function journal_main_image_update(Request $request, $id){

        $this->validate($request, [
            'image'=>'required|image'
            ]
        );

        $journal = Journal::findOrFail($id);
        $journal->clearMediaCollection('journals');
        $journal->addMediaFromRequest('image')->toMediaCollection('journals');
        flash('Journal main image updated');
        return redirect()->route('journals.edit',$journal->id);

    }

}

resources/views/journals/create.blade.php
@extends('layouts.admin.master')

@section('title', 'Journals')

@section('subtitle', 'Create')

@section('content')

<div class="col-sm-12 border bg-white p-4">
    <div class='col-lg-12'>

    {!! Form::open(['url' => route('journals.store'), 'files' => 'true']) !!}

    <div class="form-group">
        {{ Form::label('image', 'Main Image') }}<br />
        {{ Form::file('image', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('name', 'Name (unique)') }}
        {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('author_image', 'Author Image') }}<br />
        {{ Form::file('author_image', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('author_name', 'Author Name') }}
        {{ Form::text('author_name', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('author_detail', 'Author Detail') }}
        {{ Form::textarea('author_detail', null, array('class' => 'form-control my-editor', 'rows' => 3)) }}
    </div>

    <div class="form-group">
        {{ Form::label('content', 'Content') }}
        {{ Form::textarea('content', null, array('class' => 'form-control my-editor', 'rows' => 20)) }}
    </div>

    <div class="form-group">
        {{ Form::label('featured', 'Featured ') }}

        {{ Form::hidden('featured', 0) }}
        {{ Form::checkbox('featured', 1, false) }}
    </div>

    <div class="form-group">
        {{ Form::label('hidden', 'Hidden ') }}

        {{ Form::hidden('hidden', 0) }}
        {{ Form::checkbox('hidden', 1, true) }}
    </div>

    <div class="form-group">
        {{ Form::label('released_at', 'Released At ') }}
        {{ Form::date('released_at', Carbon\Carbon::now(), array('class' => 'form-control my-editor', 'required')) }}
    </div>
    
    <a class="btn btn-link" href="{{ route('journals.index') }}">Back</a> 
    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

    </div>
</div>

@endsection

@section('js')
@parent
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endsection

resources/views/journals/edit.blade.php
@extends('layouts.admin.master')

@section('title', 'Journals')
@section('subtitle', 'Edit')

@section('content')

<div class="row">

    <div class="col-sm-2 border bg-white p-1">
        <section class="dashboard-counts no-padding-bottom no-padding-top">
        <div class="row bg-white has-shadow">
            <div class="col-lg-12">
                <div class="thumbnail">
                    <h3>Main Image</h3>
                    <hr/>

                    @if(empty($journal->getMedia('journals')->first()))
                    <img width="100%" src="{{url('img/no_image.png')}}" />
                    @else
                    <img width="100%" src="{{ $journal->getMedia('journals')->first()->getUrl() }}" />
                    @endif

                    <div class="caption">
                        <br />
                        <p>
                            @if(!empty($journal->getMedia('journals')->first()))
                            <a href="{{ $journal->getMedia('journals')->first()->getUrl() }}" target="_blank" class="btn btn-primary btn-block" role="button">View Image</a>
                            @else
                            <a href="{{url('img/no_image.png')}}" target="_blank" class="btn btn-primary btn-block" role="button">View Image</a>
                            @endif

                            <a data-toggle="modal" data-target="#mainimage" class="btn btn-primary btn-block" role="button">Change Image</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        </section>

        <section class="dashboard-counts no-padding-bottom">
            <div class="row bg-white has-shadow">
                <div class="col-lg-12">
                    <div class="thumbnail">
                        <h3>Author Image</h3>
                        <hr/>

                        @if(empty($journal->getMedia('authors')->first()))
                        <img width="100%" src="{{url('img/no_image.png')}}" />
                        @else
                        <img width="100%" src="{{ $journal->getMedia('authors')->first()->getUrl() }}" />
                        @endif

                        <div class="caption">
                            <br />
                            <p>
                                @if(!empty($journal->getMedia('authors')->first()))
                                <a href="{{ $journal->getMedia('authors')->first()->getUrl() }}" target="_blank" class="btn btn-primary btn-block" role="button">View Image</a>
                                @else
                                <a href="{{url('img/no_image.png')}}" target="_blank" class="btn btn-primary btn-block" role="button">View Image</a>
                                @endif

                                <a data-toggle="modal" data-target="#authorimage" class="btn btn-primary btn-block" role="button">Change Image</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>
    <div class="col-sm-10 border bg-white p-4">
        <div class="row bg-white has-shadow">
            <div class='col-lg-12'>

                {{ Form::model($journal, array('route' => array('journals.update', $journal->id), 'method' => 'PUT', 'data-parsley-validate')) }}

                <div class="form-group">
                    {{ Form::label('name', 'Name (unique)') }}
                    {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
                </div>

                <div class="form-group">
                    {{ Form::label('title', 'Title') }}
                    {{ Form::text('title', null, array('class' => 'form-control', 'required')) }}
                </div>

                <div class="form-group">
                    {{ Form::label('author_name', 'Author Name') }}
                    {{ Form::text('author_name', null, array('class' => 'form-control', 'required')) }}
                </div>

                <div class="form-group">
                    {{ Form::label('author_detail', 'Author Detail') }}
                    {{ Form::textarea('author_detail', null, array('class' => 'form-control my-editor', 'required', 'rows' => 3)) }}
                </div>

                <div class="form-group">
                    {{ Form::label('content', 'Content') }}
                    {{ Form::textarea('content', null, array('class' => 'form-control my-editor', 'required', 'rows' => 20)) }}
                </div>

                <div class="form-group">
                    {{ Form::label('featured', 'Featured ') }}

                    {{ Form::hidden('featured', 0) }}
                    {{ Form::checkbox('featured', 1, null) }}
                </div>

                <div class="form-group">
                    {{ Form::label('hidden', 'Hidden ') }}

                    {{ Form::hidden('hidden', 0) }}
                    {{ Form::checkbox('hidden', 1, null) }}
                </div>

                <div class="form-group">
                    {{ Form::label('released_at', 'Released At ') }}
                    {{ Form::date('released_at', null, array('class' => 'form-control my-editor', 'required')) }}
                </div>

                <a class="btn btn-link" href="{{ route('journals.index') }}">Back</a> 
                {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}
            </div>
        </div>
    </div>

</div>

<div class="modal fade" id="authorimage" tabindex="-1" role="dialog" aria-labelledby="authorimage" aria-hidden="true">
    <div class="modal-dialog" role="document">
        {{ Form::model($journal, array('route' => array('journals.author.image.update', $journal->id),'files' => true, 'method' => 'PUT', 'data-parsley-validate')) }}
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Upload New Picture</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    {{ Form::label('author_image', 'Author Image') }}<br />
                    {{ Form::file('author_image', null, array('class' => 'form-control', 'required')) }}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
            </div>
        </div>
        {{ Form::close() }}
    </div>
</div>

<div class="modal fade" id="mainimage" tabindex="-1" role="dialog" aria-labelledby="mainimage" aria-hidden="true">
    <div class="modal-dialog" role="document">
        {{ Form::model($journal, array('route' => array('journals.main.image.update', $journal->id),'files' => true, 'method' => 'PUT', 'data-parsley-validate')) }}
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Upload New Picture</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    {{ Form::label('image', 'Main Image') }}<br />
                    {{ Form::file('image', null, array('class' => 'form-control', 'required')) }}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
            </div>
        </div>
        {{ Form::close() }}
    </div>
</div>

@endsection


@section('js')
@parent
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endsection

resources/views/journals/index.blade.php
@extends('layouts.admin.master')

@section('title', 'Journals')

@section('content')


<div class="card">
    <div class="card-body">
        @can('add_journals')
            <a href="{{ route('journals.create') }}" class="btn btn-success">
                <i class="fas fa-plus"></i> New
            </a>
        @endcan

        @can('edit_journal_theme')
            <a href="{{ route('themes.index') }}" class="btn btn-success">
                    <i class="fas fa-edit"></i> Update Theme</a>
        @endcan
    </div>
</div>

<br />
<div>
    <a href="{{ URL::to('journals') }}">All</a> | <a href="{{ URL::to('journals?view=trash') }}">Trash</a>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name (unique)</th>
            <th>Title</th>
            <th>Author</th>
            <th>Feature</th>
            <th>Hidden</th>
            <th>Operation</th>
        </tr>
    </thead>

    <tbody>
        @foreach ($journals as $journal)
        <tr>

            <td>{{ $journal->name }}</td>
            <td>{{ $journal->title }}</td>
            <td>{{ $journal->author_name }}</td>
            <td>@include('shared._check', ['check' => $journal->featured])</td>
            <td>@include('shared._check', ['check' => $journal->hidden])</td>

            <td>
                @include('shared._table_action_2', ['model' => $journal, 'url' => 'journals'])
            </td>
        </tr>
        @endforeach
    </tbody>

</table>
        




@endsection